baseurl = "https://research-notebook-paigecd.netlify.app"
title = "Online Research Notebook"
author = "Paige Downey"
canonifyurls = true
paginate = 3
theme = "aether"

[params]
    brand = "Paige Downey"
    description = "This is the website that contains my online research notebook for my CMPSC 580 class."
    headshotimg = "img/faceshot.jpg"
    headshotalt = "Generic grey headshot picture"

[markup]
  [markup.highlight]
    style = "igor"