baseURL = "http://research-notebook-paigecd.com/"
languageCode = "en-us"
title = "Online Research Notebook"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Paige Downey - All rights reserved"
enableEmoji = true
publishDir = "public"

[params]
  logo = "/images/pencil.png"
  description ="My Research Notes:"

[params.author]
  name = "Paige Downey"
  thumbnail = "/images/notebook.png"
  description = "Creator of this research notebook."

[params.index]
  picture = "/images/notebook.png"
  title = "Online Research Notebook"
  subtitle = "Paige Downey"
  mdtext = '''
This is the website that will contain my online research notebook for my CMPSC 580 class.\
**Please click the 'Blog' tab above to see my posts.**

'''
  alertbar = false

[params.social]
  github = "PaigeCD"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"
